# Generated by Django 5.1.15 on 2026-08-22 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={
                "ordering": ["-is_default", "-created_at"],
                "verbose_name": "Địa chỉ giao hàng",
                "verbose_name_plural": "Địa chỉ giao hàng",
            },
        ),
        migrations.AlterField(
            model_name="address",
            name="address_text",
            field=models.TextField(verbose_name="Địa chỉ chi tiết"),
        ),
        migrations.AlterField(
            model_name="address",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="address",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="customers.customer",
                verbose_name="Khách hàng",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="Địa chỉ mặc định"),
        ),
        migrations.AlterField(
            model_name="address",
            name="label",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Nhãn địa chỉ, ví dụ: "Nhà", "Công ty"',
                max_length=100,
                verbose_name="Nhãn địa chỉ",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="latitude",
            field=models.DecimalField(
                decimal_places=8, max_digits=10, verbose_name="Vĩ độ"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="longitude",
            field=models.DecimalField(
                decimal_places=8, max_digits=11, verbose_name="Kinh độ"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Số điện thoại"),
        ),
        migrations.AlterField(
            model_name="address",
            name="recipient_name",
            field=models.CharField(max_length=255, verbose_name="Người nhận"),
        ),
        migrations.AlterField(
            model_name="address",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="avatar_url",
            field=models.TextField(blank=True, default="", verbose_name="Ảnh đại diện"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày đăng ký"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Tên khách hàng"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Số điện thoại"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="zalo_user_id",
            field=models.CharField(
                db_index=True,
                help_text="Định danh Zalo của khách hàng",
                max_length=100,
                unique=True,
                verbose_name="Zalo User ID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Số điện thoại",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("STAFF", "Nhân viên"),
                    ("ADMIN", "Quản trị viên"),
                    ("CUSTOMER", "Khách hàng"),
                ],
                default="CUSTOMER",
                max_length=50,
                verbose_name="Vai trò",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Đang hoạt động"), ("INACTIVE", "Ngưng hoạt động")],
                default="ACTIVE",
                max_length=50,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
        migrations.AlterField(
            model_name="user",
            name="zalo_user_id",
            field=models.CharField(
                blank=True,
                help_text="Định danh Zalo nhận thông báo OA",
                max_length=100,
                null=True,
                verbose_name="Zalo User ID",
            ),
        ),
    ]
