# Generated by Django 5.1.15 on 2026-09-06 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_alter_address_options_alter_address_address_text_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customer",
            name="customers_zalo_us_35bbe2_idx",
        ),
    ]
