# Generated by Django 5.1.15 on 2026-08-22 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_alter_address_options_alter_address_address_text_and_more"),
        ("notifications", "0002_initial"),
        ("orders", "0004_alter_order_delivery_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Thời gian gửi"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="customers.customer",
                verbose_name="Khách hàng",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="Đã đọc"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(verbose_name="Nội dung thông báo"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="orders.order",
                verbose_name="Đơn hàng",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời gian đọc"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Tiêu đề"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("ORDER_STATUS", "Trạng thái đơn hàng"),
                    ("PROMOTION", "Khuyến mãi"),
                ],
                default="ORDER_STATUS",
                max_length=50,
                verbose_name="Loại thông báo",
            ),
        ),
    ]
