# Generated by Django 5.1.15 on 2026-09-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_alter_notification_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZaloOACredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "oa_id",
                    models.CharField(
                        help_text="Định danh OA trên Zalo",
                        max_length=50,
                        unique=True,
                        verbose_name="Zalo OA ID",
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        help_text="Token truy cập Zalo OpenAPI (thời hạn 25 giờ)",
                        verbose_name="Access Token",
                    ),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        help_text="Token làm mới dùng 1 lần (thời hạn 3 tháng)",
                        verbose_name="Refresh Token",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Mốc thời gian access token hết hiệu lực",
                        verbose_name="Thời gian hết hạn",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Cập nhật lần cuối"
                    ),
                ),
            ],
            options={
                "verbose_name": "Zalo OA Credential",
                "verbose_name_plural": "Zalo OA Credentials",
                "db_table": "zalo_oa_credentials",
            },
        ),
    ]
