# Generated by Django 5.1.15 on 2026-08-22 03:12

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShopConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shop_name", models.CharField(default="Bếp Dì 6", max_length=255)),
                (
                    "hotline",
                    models.CharField(blank=True, default="0901234567", max_length=20),
                ),
                (
                    "address_text",
                    models.TextField(
                        blank=True,
                        default="123 Đường Số 1, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh",
                    ),
                ),
                ("announcement_banner", models.TextField(blank=True, default="")),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("10.7769"), max_digits=10
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("106.7009"), max_digits=11
                    ),
                ),
                (
                    "max_delivery_radius_km",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("7.0"), max_digits=4
                    ),
                ),
                (
                    "haversine_multiplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.3"), max_digits=3
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(
                        default=True, help_text="Bật / tắt nhận đơn hàng trực tuyến"
                    ),
                ),
                (
                    "open_time",
                    models.TimeField(
                        blank=True, help_text="Giờ mở cửa (VD: 07:00)", null=True
                    ),
                ),
                (
                    "close_time",
                    models.TimeField(
                        blank=True, help_text="Giờ đóng cửa (VD: 21:30)", null=True
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Giá trị đơn hàng tối thiểu để được đặt giao hàng (0 = không giới hạn)",
                        max_digits=12,
                    ),
                ),
                (
                    "min_order_for_freeship",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Ngưỡng giá trị đơn hàng được miễn phí giao hàng (0 = không áp dụng)",
                        max_digits=12,
                    ),
                ),
                (
                    "shipping_tiers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Bảng bậc thang phí ship: [{from_km, to_km, fee}]",
                    ),
                ),
                (
                    "vietqr_bank_id",
                    models.CharField(
                        default="MB",
                        help_text="Mã ngân hàng (VD: MB, VCB, TCB)",
                        max_length=20,
                    ),
                ),
                (
                    "vietqr_account_no",
                    models.CharField(
                        blank=True,
                        default="0987654321",
                        help_text="Số tài khoản ngân hàng nhận tiền",
                        max_length=50,
                    ),
                ),
                (
                    "vietqr_account_name",
                    models.CharField(
                        default="BEP DI 6",
                        help_text="Tên chủ tài khoản",
                        max_length=255,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cấu hình Quán",
                "verbose_name_plural": "Cấu hình Quán",
                "db_table": "shop_configs",
            },
        ),
    ]
