# Generated by Django 5.1.15 on 2026-08-22 12:45

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopconfig",
            name="address_text",
            field=models.TextField(
                blank=True,
                default="123 Đường Số 1, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh",
                verbose_name="Địa chỉ cửa hàng",
            ),
        ),
        migrations.AlterField(
            model_name="shopconfig",
            name="announcement_banner",
            field=models.TextField(
                blank=True, default="", verbose_name="Thông báo banner quán"
            ),
        ),
        migrations.AlterField(
            model_name="shopconfig",
            name="close_time",
            field=models.TimeField(
                blank=True,
                help_text="Giờ đóng cửa (VD: 21:30)",
                null=True,
                verbose_name="Giờ đóng cửa",
            ),
        ),
        migrations.AlterField(
            model_name="shopconfig",
            name="haversine_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.3"),
                max_digits=3,
                verbose_name="Hệ số uốn lượn đường đi",
            ),
        ),
        migrations.AlterField(
            model_name="shopconfig",
            name="hotline",
            field=models.CharField(
                blank=True,
                default="0901234567",
                max_length=20,
                verbose_name="Hotline CSKH",
            ),
        ),
        migrations.AlterField(
            model_name="shopconfig",
            name="is_open",
            field=models.BooleanField(
                default=True,
                help_text="Bật / tắt nhận đơn hàng trực tuyến",
                verbose_name="Đang mở cửa nhận đơn",
            ),
        ),
        migrations.AlterField(
            model_name="shopconfig",
            name="latitude",
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal("10.7769"),
                max_digits=10,
                verbose_name="Vĩ độ quán",
            ),
        ),
        migrations.AlterField(
            model_name="shopconfig",
            name="longitude",
            field=models.DecimalField(
                decimal_places=8,
                default=Decimal("106.7009"),
                max_digits=11,
                verbose_name="Kinh độ quán",
            ),
        ),
        migrations.AlterField(
            model_name="shopconfig",
            name="max_delivery_radius_km",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("7.0"),
                max_digits=4,
                verbose_name="Bán kính giao tối đa (km)",
            ),
        ),
        migrations.AlterField(
            model_name="shopconfig",
            name="min_order_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Giá trị đơn hàng tối thiểu để được đặt giao hàng (0 = không giới hạn)",
                max_digits=12,
                verbose_name="Đơn hàng tối thiểu",
            ),
        ),
        migrations.AlterField(
            model_name="shopconfig",
            name="min_order_for_freeship",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Ngưỡng giá trị đơn hàng được miễn phí giao hàng (0 = không áp dụng)",
                max_digits=12,
                verbose_name="Ngưỡng Freeship",
            ),
        ),
        migrations.AlterField(
            model_name="shopconfig",
            name="open_time",
            field=models.TimeField(
                blank=True,
                help_text="Giờ mở cửa (VD: 07:00)",
                null=True,
                verbose_name="Giờ mở cửa",
            ),
        ),
        migrations.AlterField(
            model_name="shopconfig",
            name="shipping_tiers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Bảng bậc thang phí ship: [{from_km, to_km, fee}]",
                verbose_name="Bảng bậc thang phí ship",
            ),
        ),
        migrations.AlterField(
            model_name="shopconfig",
            name="shop_name",
            field=models.CharField(
                default="Bếp Dì 6", max_length=255, verbose_name="Tên cửa hàng"
            ),
        ),
        migrations.AlterField(
            model_name="shopconfig",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Cập nhật lần cuối"),
        ),
        migrations.AlterField(
            model_name="shopconfig",
            name="vietqr_account_name",
            field=models.CharField(
                default="BEP DI 6",
                help_text="Tên chủ tài khoản",
                max_length=255,
                verbose_name="Tên chủ tài khoản",
            ),
        ),
        migrations.AlterField(
            model_name="shopconfig",
            name="vietqr_account_no",
            field=models.CharField(
                blank=True,
                default="0987654321",
                help_text="Số tài khoản ngân hàng nhận tiền",
                max_length=50,
                verbose_name="Số tài khoản",
            ),
        ),
        migrations.AlterField(
            model_name="shopconfig",
            name="vietqr_bank_id",
            field=models.CharField(
                default="MB",
                help_text="Mã ngân hàng (VD: MB, VCB, TCB)",
                max_length=20,
                verbose_name="Ngân hàng VietQR",
            ),
        ),
    ]
