# Generated by Django 5.1.15 on 2026-08-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0002_alter_shopconfig_address_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopconfig",
            name="prep_time_minutes",
            field=models.PositiveIntegerField(
                default=20,
                help_text="Thời gian chuẩn bị món ước tính mặc định của quán (phút)",
                verbose_name="Thời gian chuẩn bị món (phút)",
            ),
        ),
    ]
