# Generated by Django 5.1.15 on 2026-08-21 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Số tiền cố định"),
                            ("PERCENTAGE", "Phần trăm"),
                        ],
                        default="FIXED",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "minimum_order_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "maximum_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Áp dụng khi discount_type là PERCENTAGE",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "usage_limit",
                    models.IntegerField(
                        default=0,
                        help_text="Tổng lượt dùng toàn hệ thống (0 = không giới hạn)",
                    ),
                ),
                (
                    "usage_per_customer",
                    models.IntegerField(
                        default=1, help_text="Lượt dùng tối đa trên từng khách"
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Đang hoạt động"),
                            ("INACTIVE", "Ngưng hoạt động"),
                        ],
                        default="ACTIVE",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mã giảm giá",
                "verbose_name_plural": "Mã giảm giá",
                "db_table": "vouchers",
                "indexes": [
                    models.Index(
                        fields=["code", "status"], name="vouchers_code_3896c5_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VoucherUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Đã áp dụng"),
                            ("RELEASED", "Đã hoàn trả/nhả mã"),
                        ],
                        default="APPLIED",
                        max_length=30,
                    ),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucher_usages",
                        to="customers.customer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucher_usages",
                        to="orders.order",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="vouchers.voucher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử dùng mã giảm giá",
                "verbose_name_plural": "Lịch sử dùng mã giảm giá",
                "db_table": "voucher_usages",
                "indexes": [
                    models.Index(
                        fields=["voucher", "customer"],
                        name="voucher_usa_voucher_276385_idx",
                    )
                ],
            },
        ),
    ]
