# Generated by Django 5.1.15 on 2026-08-22 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_alter_address_options_alter_address_address_text_and_more"),
        ("orders", "0004_alter_order_delivery_type"),
        ("vouchers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="code",
            field=models.CharField(
                db_index=True, max_length=50, unique=True, verbose_name="Mã giảm giá"
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="discount_type",
            field=models.CharField(
                choices=[("FIXED", "Số tiền cố định"), ("PERCENTAGE", "Phần trăm")],
                default="FIXED",
                max_length=20,
                verbose_name="Loại giảm giá",
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="discount_value",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Mức giảm"
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="end_at",
            field=models.DateTimeField(verbose_name="Thời gian kết thúc"),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="maximum_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Áp dụng khi discount_type là PERCENTAGE",
                max_digits=12,
                null=True,
                verbose_name="Giảm tối đa",
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="minimum_order_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Đơn tối thiểu",
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Tên chương trình"),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="start_at",
            field=models.DateTimeField(verbose_name="Thời gian bắt đầu"),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Đang hoạt động"), ("INACTIVE", "Ngưng hoạt động")],
                default="ACTIVE",
                max_length=30,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="usage_limit",
            field=models.IntegerField(
                default=0,
                help_text="Tổng lượt dùng toàn hệ thống (0 = không giới hạn)",
                verbose_name="Giới hạn toàn hệ thống",
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="usage_per_customer",
            field=models.IntegerField(
                default=1,
                help_text="Lượt dùng tối đa trên từng khách",
                verbose_name="Giới hạn mỗi khách",
            ),
        ),
        migrations.AlterField(
            model_name="voucherusage",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voucher_usages",
                to="customers.customer",
                verbose_name="Khách hàng",
            ),
        ),
        migrations.AlterField(
            model_name="voucherusage",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Số tiền đã giảm"
            ),
        ),
        migrations.AlterField(
            model_name="voucherusage",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voucher_usages",
                to="orders.order",
                verbose_name="Đơn hàng",
            ),
        ),
        migrations.AlterField(
            model_name="voucherusage",
            name="status",
            field=models.CharField(
                choices=[("APPLIED", "Đã áp dụng"), ("RELEASED", "Đã hoàn trả/nhả mã")],
                default="APPLIED",
                max_length=30,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="voucherusage",
            name="used_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Thời gian dùng"
            ),
        ),
        migrations.AlterField(
            model_name="voucherusage",
            name="voucher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usages",
                to="vouchers.voucher",
                verbose_name="Mã giảm giá",
            ),
        ),
    ]
