# Generated by Django 5.1.15 on 2026-08-21 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("COD", "Tiền mặt khi nhận hàng"),
                            ("BANK_TRANSFER", "Chuyển khoản (VietQR)"),
                        ],
                        default="COD",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNPAID", "Chưa thanh toán"),
                            ("PENDING", "Đang xử lý / Chờ đối soát"),
                            ("PAID", "Đã thanh toán"),
                            ("FAILED", "Thất bại"),
                            ("REFUNDED", "Đã hoàn tiền"),
                        ],
                        default="UNPAID",
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "transaction_reference",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("qr_code_url", models.TextField(blank=True, default="")),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actual_paid_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Số tiền thực nhận (VietQR)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, default="", help_text="Ghi chú lệch tiền"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="orders.order",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nhân viên xác nhận thanh toán",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Thanh toán",
                "verbose_name_plural": "Thanh toán",
                "db_table": "payments",
            },
        ),
    ]
