# Generated by Django 5.1.15 on 2026-08-22 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_order_delivery_type"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "verbose_name": "Giao dịch thanh toán",
                "verbose_name_plural": "Giao dịch thanh toán",
            },
        ),
        migrations.AlterField(
            model_name="payment",
            name="actual_paid_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Số tiền thực nhận (VietQR)",
                max_digits=12,
                null=True,
                verbose_name="Số tiền thực nhận",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Số tiền"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("COD", "Tiền mặt khi nhận hàng"),
                    ("BANK_TRANSFER", "Chuyển khoản (VietQR)"),
                ],
                default="COD",
                max_length=30,
                verbose_name="Phương thức thanh toán",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Ghi chú lệch tiền",
                verbose_name="Ghi chú",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="orders.order",
                verbose_name="Đơn hàng",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Thời gian thanh toán"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="qr_code_url",
            field=models.TextField(
                blank=True, default="", verbose_name="Link mã VietQR"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("UNPAID", "Chưa thanh toán"),
                    ("PENDING", "Đang xử lý / Chờ đối soát"),
                    ("PAID", "Đã thanh toán"),
                    ("FAILED", "Thất bại"),
                    ("REFUNDED", "Đã hoàn tiền"),
                ],
                default="UNPAID",
                max_length=30,
                verbose_name="Trạng thái thanh toán",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_reference",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Mã giao dịch"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Nhân viên xác nhận thanh toán",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người xác nhận",
            ),
        ),
    ]
