export const ADMIN_COPY = {
  tabs: {
    dashboard: "Tổng quan",
    kitchen: "Bếp",
    manage: "Quản lý",
    settings: "Cài đặt",
    backToShop: "Khách",
  },
  dashboard: {
    greeting: "Xin chào",
    pendingOrders: "Đơn chờ xử lý",
    todayRevenue: "Doanh thu hôm nay",
    menuItems: "Món trong menu",
    activeVouchers: "Khuyến mãi đang chạy",
    goToKitchen: "Vào Bếp",
    shortcuts: "Lối tắt tác vụ",
    operations: "Thông tin vận hành",
  },
  menu: {
    categories: "Danh mục món",
    products: "Danh sách món ăn",
    addCategory: "Thêm danh mục",
    addProduct: "Thêm món",
    editCategory: "Sửa danh mục",
    editProduct: "Chỉnh sửa món ăn",
    deleteConfirm: "Bạn có chắc muốn xoá?",
    emptyCategories: "Chưa có danh mục nào",
    emptyProducts: "Chưa có món ăn nào",
  },
  vouchers: {
    title: "Quản Lý Voucher",
    addVoucher: "Tạo mã",
    editVoucher: "Chỉnh sửa voucher",
    all: "Tất cả",
    active: "Đang áp dụng",
    inactive: "Đã tạm dừng",
    emptyList: "Chưa có mã giảm giá nào",
    discountPercent: "Giảm theo phần trăm (%)",
    discountFixed: "Giảm tiền trực tiếp (₫)",
  },
  settings: {
    title: "Cài Đặt Vận Hành Quán",
    storeInfo: "Thông tin cửa hàng",
    hours: "Thời gian hoạt động",
    delivery: "Giao hàng & Phí ship",
    payment: "Tài khoản nhận tiền VietQR",
    saveChanges: "Lưu thay đổi cấu hình",
    savedSuccess: "Lưu cấu hình quán thành công!",
    savedError: "Lưu cấu hình thất bại, vui lòng thử lại",
  },
  manage: {
    title: "Trung Tâm Quản Lý",
    menuSection: "Thực Đơn & Danh Mục",
    promotionSection: "Khuyến Mãi & Tiếp Thị",
    customerSection: "Khách Hàng & Dữ Liệu",
  },
  common: {
    save: "Lưu",
    cancel: "Huỷ",
    delete: "Xoá",
    edit: "Sửa",
    create: "Tạo mới",
    loading: "Đang tải...",
    comingSoon: "Tính năng đang được phát triển ở phiên bản kế tiếp.",
    goBack: "Quay lại",
  },
} as const;
