# Generated by Django 5.1.15 on 2026-08-21 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(help_text="Snapshot tên món", max_length=255),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Snapshot giá tại thời điểm đặt",
                        max_digits=12,
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Món trong đơn hàng",
                "verbose_name_plural": "Món trong đơn hàng",
                "db_table": "order_items",
            },
        ),
        migrations.CreateModel(
            name="OrderItemOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_name",
                    models.CharField(help_text="Snapshot tên tùy chọn", max_length=255),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Snapshot giá tùy chọn",
                        max_digits=12,
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "Tùy chọn món trong đơn",
                "verbose_name_plural": "Tùy chọn món trong đơn",
                "db_table": "order_item_options",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="UPDATE_ORDER_STATUS, VERIFY_PAYMENT...",
                        max_length=100,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="ORDER, PRODUCT, PAYMENT...", max_length=50
                    ),
                ),
                ("entity_id", models.BigIntegerField()),
                ("old_data", models.JSONField(blank=True, null=True)),
                ("new_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nhật ký kiểm toán",
                "verbose_name_plural": "Nhật ký kiểm toán",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_code",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        help_text="Định danh chống trùng đơn", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_CONFIRMATION", "Chờ xác nhận"),
                            ("CONFIRMED", "Đã xác nhận"),
                            ("PREPARING", "Đang chuẩn bị"),
                            ("READY", "Sẵn sàng giao"),
                            ("DELIVERING", "Đang giao hàng"),
                            ("COMPLETED", "Hoàn thành"),
                            ("CANCELLED", "Đã hủy"),
                        ],
                        default="PENDING_CONFIRMATION",
                        max_length=50,
                    ),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[("ASAP", "Giao ngay"), ("SCHEDULED", "Hẹn giờ")],
                        default="ASAP",
                        max_length=20,
                    ),
                ),
                ("recipient_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("delivery_address", models.TextField()),
                (
                    "delivery_latitude",
                    models.DecimalField(decimal_places=8, max_digits=10),
                ),
                (
                    "delivery_longitude",
                    models.DecimalField(decimal_places=8, max_digits=11),
                ),
                (
                    "distance_km",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("COD", "Tiền mặt khi nhận hàng"),
                            ("BANK_TRANSFER", "Chuyển khoản (VietQR)"),
                        ],
                        default="COD",
                        max_length=30,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("scheduled_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancellation_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đơn hàng",
                "verbose_name_plural": "Đơn hàng",
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
