# Generated by Django 5.1.15 on 2026-08-22 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
        ("orders", "0002_initial"),
        ("vouchers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cancellation_reason",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Lý do hủy"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Hủy lúc"),
        ),
        migrations.AlterField(
            model_name="order",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Hoàn tất lúc"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Xác nhận lúc"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Thời gian đặt"),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="customers.customer",
                verbose_name="Khách hàng",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(verbose_name="Địa chỉ giao"),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_latitude",
            field=models.DecimalField(
                decimal_places=8, max_digits=10, verbose_name="Vĩ độ giao"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_longitude",
            field=models.DecimalField(
                decimal_places=8, max_digits=11, verbose_name="Kinh độ giao"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[("ASAP", "Giao ngay"), ("SCHEDULED", "Hẹn giờ")],
                default="ASAP",
                max_length=20,
                verbose_name="Hình thức giao",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, verbose_name="Giảm giá"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="distance_km",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=6,
                verbose_name="Khoảng cách (km)",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="idempotency_key",
            field=models.CharField(
                help_text="Định danh chống trùng đơn",
                max_length=100,
                verbose_name="Khóa chống trùng",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="note",
            field=models.TextField(blank=True, default="", verbose_name="Ghi chú đơn"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_code",
            field=models.CharField(
                db_index=True, max_length=32, unique=True, verbose_name="Mã đơn hàng"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("COD", "Tiền mặt khi nhận hàng"),
                    ("BANK_TRANSFER", "Chuyển khoản (VietQR)"),
                ],
                default="COD",
                max_length=30,
                verbose_name="Hình thức thanh toán",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Số điện thoại"),
        ),
        migrations.AlterField(
            model_name="order",
            name="recipient_name",
            field=models.CharField(max_length=255, verbose_name="Người nhận"),
        ),
        migrations.AlterField(
            model_name="order",
            name="scheduled_delivery_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Hẹn giờ giao lúc"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_fee",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=12, verbose_name="Phí ship"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_CONFIRMATION", "Chờ xác nhận"),
                    ("CONFIRMED", "Đã xác nhận"),
                    ("PREPARING", "Đang chuẩn bị"),
                    ("READY", "Sẵn sàng giao"),
                    ("DELIVERING", "Đang giao hàng"),
                    ("COMPLETED", "Hoàn thành"),
                    ("CANCELLED", "Đã hủy"),
                ],
                default="PENDING_CONFIRMATION",
                max_length=50,
                verbose_name="Trạng thái đơn",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Tạm tính"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Tổng tiền"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Cập nhật lúc"),
        ),
        migrations.AlterField(
            model_name="order",
            name="voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="vouchers.voucher",
                verbose_name="Voucher áp dụng",
            ),
        ),
    ]
