# Generated by Django 5.1.15 on 2026-08-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_order_cancellation_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("DELIVERY", "Giao tận nơi"),
                    ("PICKUP", "Tự đến lấy tại quán"),
                    ("ASAP", "Giao ngay (Cũ)"),
                    ("SCHEDULED", "Hẹn giờ (Cũ)"),
                ],
                default="DELIVERY",
                max_length=20,
                verbose_name="Hình thức nhận hàng",
            ),
        ),
    ]
