# Generated by Django 5.2.17 on 2026-09-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_alter_order_delivery_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INTERNAL", "Shipper của quán"),
                    ("AHAMOVE", "Ahamove"),
                    ("GRAB", "GrabExpress"),
                    ("OTHER", "Đối tác khác"),
                ],
                default="",
                max_length=20,
                verbose_name="Đơn vị giao hàng",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipper_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Tên tài xế/Shipper",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipper_phone",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="SĐT tài xế"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipper_tracking_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Mã vận đơn / Tracking",
            ),
        ),
    ]
