# Generated by Django 5.1.15 on 2026-08-21 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("image_url", models.TextField(blank=True, default="")),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Đang hoạt động"),
                            ("INACTIVE", "Ngưng hoạt động"),
                        ],
                        default="ACTIVE",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Danh mục món",
                "verbose_name_plural": "Danh mục món",
                "db_table": "categories",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="OptionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Ví dụ: "Chọn nước", "Thêm topping"', max_length=255
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("min_select", models.IntegerField(default=0)),
                ("max_select", models.IntegerField(default=1)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Nhóm tùy chọn",
                "verbose_name_plural": "Nhóm tùy chọn",
                "db_table": "option_groups",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Giá cộng thêm",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("AVAILABLE", "Đang bán"), ("INACTIVE", "Ngưng bán")],
                        default="AVAILABLE",
                        max_length=50,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "option_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="menu.optiongroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tùy chọn",
                "verbose_name_plural": "Tùy chọn",
                "db_table": "options",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("image_url", models.TextField(blank=True, default="")),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Đang bán"),
                            ("OUT_OF_STOCK", "Hết hàng"),
                            ("INACTIVE", "Ngưng bán"),
                        ],
                        default="AVAILABLE",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="menu.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Món ăn",
                "verbose_name_plural": "Món ăn",
                "db_table": "products",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="optiongroup",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="option_groups",
                to="menu.product",
            ),
        ),
    ]
