# Generated by Django 5.1.15 on 2026-08-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="File ảnh danh mục",
                null=True,
                upload_to="categories/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="File ảnh món ăn",
                null=True,
                upload_to="products/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image_url",
            field=models.TextField(
                blank=True,
                default="",
                help_text="URL ảnh danh mục (tự động lấy từ file tải lên hoặc dán link ngoài)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.TextField(
                blank=True,
                default="",
                help_text="URL ảnh món ăn (tự động lấy từ file tải lên hoặc dán link ngoài)",
            ),
        ),
    ]
