# Generated by Django 5.1.15 on 2026-08-22 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_category_image_product_image_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="option",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "Tùy chọn món",
                "verbose_name_plural": "Tùy chọn món",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Mô tả"),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="File ảnh danh mục",
                null=True,
                upload_to="categories/%Y/%m/",
                verbose_name="File ảnh",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image_url",
            field=models.TextField(
                blank=True,
                default="",
                help_text="URL ảnh danh mục (tự động lấy từ file tải lên hoặc dán link ngoài)",
                verbose_name="Đường dẫn ảnh",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Tên danh mục"),
        ),
        migrations.AlterField(
            model_name="category",
            name="sort_order",
            field=models.IntegerField(default=0, verbose_name="Thứ tự hiển thị"),
        ),
        migrations.AlterField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Đang hoạt động"), ("INACTIVE", "Ngưng hoạt động")],
                default="ACTIVE",
                max_length=50,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
        migrations.AlterField(
            model_name="option",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Tên tùy chọn"),
        ),
        migrations.AlterField(
            model_name="option",
            name="option_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="menu.optiongroup",
                verbose_name="Nhóm tùy chọn",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Giá cộng thêm",
                max_digits=12,
                verbose_name="Giá cộng thêm",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="sort_order",
            field=models.IntegerField(default=0, verbose_name="Thứ tự hiển thị"),
        ),
        migrations.AlterField(
            model_name="option",
            name="status",
            field=models.CharField(
                choices=[("AVAILABLE", "Đang bán"), ("INACTIVE", "Ngưng bán")],
                default="AVAILABLE",
                max_length=50,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="optiongroup",
            name="is_required",
            field=models.BooleanField(default=False, verbose_name="Bắt buộc chọn"),
        ),
        migrations.AlterField(
            model_name="optiongroup",
            name="max_select",
            field=models.IntegerField(default=1, verbose_name="Số lượng chọn tối đa"),
        ),
        migrations.AlterField(
            model_name="optiongroup",
            name="min_select",
            field=models.IntegerField(
                default=0, verbose_name="Số lượng chọn tối thiểu"
            ),
        ),
        migrations.AlterField(
            model_name="optiongroup",
            name="name",
            field=models.CharField(
                help_text='Ví dụ: "Chọn nước", "Thêm topping"',
                max_length=255,
                verbose_name="Tên nhóm tùy chọn",
            ),
        ),
        migrations.AlterField(
            model_name="optiongroup",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="option_groups",
                to="menu.product",
                verbose_name="Món ăn",
            ),
        ),
        migrations.AlterField(
            model_name="optiongroup",
            name="sort_order",
            field=models.IntegerField(default=0, verbose_name="Thứ tự hiển thị"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="menu.category",
                verbose_name="Danh mục",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Mô tả"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="File ảnh món ăn",
                null=True,
                upload_to="products/%Y/%m/",
                verbose_name="File ảnh",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.TextField(
                blank=True,
                default="",
                help_text="URL ảnh món ăn (tự động lấy từ file tải lên hoặc dán link ngoài)",
                verbose_name="Đường dẫn ảnh",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Tên món"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Giá bán"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Đang bán"),
                    ("OUT_OF_STOCK", "Hết hàng"),
                    ("INACTIVE", "Ngưng bán"),
                ],
                default="AVAILABLE",
                max_length=50,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
        ),
    ]
