# Generated by Django 5.1.15 on 2026-08-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_alter_option_options_alter_category_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="sort_order",
            field=models.IntegerField(
                db_index=True, default=0, verbose_name="Thứ tự hiển thị"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Đang hoạt động"), ("INACTIVE", "Ngưng hoạt động")],
                db_index=True,
                default="ACTIVE",
                max_length=50,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="sort_order",
            field=models.IntegerField(
                db_index=True, default=0, verbose_name="Thứ tự hiển thị"
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="status",
            field=models.CharField(
                choices=[("AVAILABLE", "Đang bán"), ("INACTIVE", "Ngưng bán")],
                db_index=True,
                default="AVAILABLE",
                max_length=50,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AlterField(
            model_name="optiongroup",
            name="sort_order",
            field=models.IntegerField(
                db_index=True, default=0, verbose_name="Thứ tự hiển thị"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("AVAILABLE", "Đang bán"),
                    ("OUT_OF_STOCK", "Hết hàng"),
                    ("INACTIVE", "Ngưng bán"),
                ],
                db_index=True,
                default="AVAILABLE",
                max_length=50,
                verbose_name="Trạng thái",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["status", "sort_order"], name="idx_cat_status_sort"
            ),
        ),
        migrations.AddIndex(
            model_name="option",
            index=models.Index(
                fields=["option_group", "status"], name="idx_opt_group_status"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "category"], name="idx_prod_status_cat"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "status"], name="idx_prod_cat_status"
            ),
        ),
    ]
