# Generated by Django 5.1.15 on 2026-08-28 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0004_alter_category_sort_order_alter_category_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promotional_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Giá bán trong thời gian khuyến mãi",
                        max_digits=12,
                        verbose_name="Giá ưu đãi",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Đang kích hoạt"
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="Để trống = áp dụng ngay",
                        null=True,
                        verbose_name="Hiệu lực từ",
                    ),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True,
                        help_text="Để trống = không giới hạn",
                        null=True,
                        verbose_name="Hết hạn lúc",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ví dụ: Flash sale 12h, Combo cuối tuần",
                        max_length=255,
                        verbose_name="Ghi chú nội bộ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotions",
                        to="menu.product",
                        verbose_name="Món ăn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giá ưu đãi",
                "verbose_name_plural": "Giá ưu đãi",
                "db_table": "product_promotions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "is_active"], name="idx_promo_product_active"
                    )
                ],
            },
        ),
    ]
